export { LoginPage } from './login';
export { MainPage } from './main';
export { NotFoundPage } from './404-not-found';
export { ResetPassPage } from './reset-password';
export { RegPage } from './register';
export { ProfilePage } from './profile';
export { IngredientsPage } from './ingredients';
export { ForgotPassPage } from './forgot-password';
export { OrdersPage } from './orders';